### ISSUE TITLE
AttributeError when used with pytest 3.4.0

### ISSUE THREAD

**Issue by mattsb42-aws** [Frozenball/pytest-sugar#131]
I can't quite tell if this is an issue with this package or pluggy, but adding this package is when the error shows up. This error did not manifest in pytest <3.4.0.

When reporting an issue, include a way to reproduce the bug. For example:

#### Command used to run py.test
Tox trigger:
`tox -re py27-local`

Actually runs:
`pytest --cov aws_encryption_sdk_cli -m local -l`

#### Test file
https://github.com/awslabs/aws-encryption-sdk-cli/tree/master/test

#### Output
````
186590df9307:aws-encryption-sdk-cli bullocm$ tox -re py27-local
GLOB sdist-make: /Users/bullocm/git/aws-encryption-sdk-cli/setup.py
py27-local recreate: /Users/bullocm/git/aws-encryption-sdk-cli/.tox/py27-local
py27-local installdeps: mock, pytest>3.3.0, pytest-cov, pytest-mock, pytest-sugar
py27-local inst: /Users/bullocm/git/aws-encryption-sdk-cli/.tox/dist/aws-encryption-sdk-cli-1.1.4.zip
py27-local installed: asn1crypto==0.24.0,attrs==17.4.0,aws-encryption-sdk==1.3.3,aws-encryption-sdk-cli==1.1.4,boto3==1.5.22,botocore==1.8.36,cffi==1.11.4,coverage==4.4.2,cryptography==2.1.4,docutils==0.14,enum34==1.1.6,funcsigs==1.0.2,futures==3.2.0,idna==2.6,ipaddress==1.0.19,jmespath==0.9.3,mock==2.0.0,pbr==3.1.1,pluggy==0.6.0,py==1.5.2,pycparser==2.18,pytest==3.4.0,pytest-cov==2.5.1,pytest-mock==1.6.3,pytest-sugar==0.9.0,python-dateutil==2.6.1,s3transfer==0.1.12,six==1.11.0,termcolor==1.1.0,typing==3.6.4,wrapt==1.10.11
py27-local runtests: PYTHONHASHSEED='3679247349'
py27-local runtests: commands[0] | pytest -m local -l
Test session starts (platform: darwin, Python 2.7.13, pytest 3.4.0, pytest-sugar 0.9.0)
rootdir: /Users/bullocm/git/aws-encryption-sdk-cli, inifile: setup.cfg
plugins: sugar-0.9.0, mock-1.6.3, cov-2.5.1

 test/unit/test_arg_parsing.py ✓                                                                                                                                                                    0%           INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/bullocm/git/aws-encryption-sdk-cli/.tox/py27-local/lib/python2.7/site-packages/_pytest/main.py", line 100, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/Users/bullocm/git/aws-encryption-sdk-cli/.tox/py27-local/lib/python2.7/site-packages/_pytest/main.py", line 138, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/Users/bullocm/git/aws-encryption-sdk-cli/.tox/py27-local/lib/python2.7/site-packages/pluggy/__init__.py", line 617, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/Users/bullocm/git/aws-encryption-sdk-cli/.tox/py27-local/lib/python2.7/site-packages/pluggy/__init__.py", line 222, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/bullocm/git/aws-encryption-sdk-cli/.tox/py27-local/lib/python2.7/site-packages/pluggy/__init__.py", line 216, in <lambda>
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>   File "/Users/bullocm/git/aws-encryption-sdk-cli/.tox/py27-local/lib/python2.7/site-packages/pluggy/callers.py", line 201, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/Users/bullocm/git/aws-encryption-sdk-cli/.tox/py27-local/lib/python2.7/site-packages/pluggy/callers.py", line 77, in get_result
INTERNALERROR>     _reraise(*ex)  # noqa
INTERNALERROR>   File "/Users/bullocm/git/aws-encryption-sdk-cli/.tox/py27-local/lib/python2.7/site-packages/pluggy/callers.py", line 180, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/Users/bullocm/git/aws-encryption-sdk-cli/.tox/py27-local/lib/python2.7/site-packages/_pytest/main.py", line 161, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "/Users/bullocm/git/aws-encryption-sdk-cli/.tox/py27-local/lib/python2.7/site-packages/pluggy/__init__.py", line 617, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/Users/bullocm/git/aws-encryption-sdk-cli/.tox/py27-local/lib/python2.7/site-packages/pluggy/__init__.py", line 222, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/bullocm/git/aws-encryption-sdk-cli/.tox/py27-local/lib/python2.7/site-packages/pluggy/__init__.py", line 216, in <lambda>
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>   File "/Users/bullocm/git/aws-encryption-sdk-cli/.tox/py27-local/lib/python2.7/site-packages/pluggy/callers.py", line 201, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/Users/bullocm/git/aws-encryption-sdk-cli/.tox/py27-local/lib/python2.7/site-packages/pluggy/callers.py", line 77, in get_result
INTERNALERROR>     _reraise(*ex)  # noqa
INTERNALERROR>   File "/Users/bullocm/git/aws-encryption-sdk-cli/.tox/py27-local/lib/python2.7/site-packages/pluggy/callers.py", line 180, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/Users/bullocm/git/aws-encryption-sdk-cli/.tox/py27-local/lib/python2.7/site-packages/_pytest/runner.py", line 64, in pytest_runtest_protocol
INTERNALERROR>     nodeid=item.nodeid, location=item.location,
INTERNALERROR>   File "/Users/bullocm/git/aws-encryption-sdk-cli/.tox/py27-local/lib/python2.7/site-packages/pluggy/__init__.py", line 617, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/Users/bullocm/git/aws-encryption-sdk-cli/.tox/py27-local/lib/python2.7/site-packages/pluggy/__init__.py", line 222, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/bullocm/git/aws-encryption-sdk-cli/.tox/py27-local/lib/python2.7/site-packages/pluggy/__init__.py", line 216, in <lambda>
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>   File "/Users/bullocm/git/aws-encryption-sdk-cli/.tox/py27-local/lib/python2.7/site-packages/pluggy/callers.py", line 201, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/Users/bullocm/git/aws-encryption-sdk-cli/.tox/py27-local/lib/python2.7/site-packages/pluggy/callers.py", line 77, in get_result
INTERNALERROR>     _reraise(*ex)  # noqa
INTERNALERROR>   File "/Users/bullocm/git/aws-encryption-sdk-cli/.tox/py27-local/lib/python2.7/site-packages/pluggy/callers.py", line 180, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/Users/bullocm/git/aws-encryption-sdk-cli/.tox/py27-local/lib/python2.7/site-packages/_pytest/terminal.py", line 315, in pytest_runtest_logfinish
INTERNALERROR>     last_item = len(self._progress_nodeids_reported) == self._session.testscollected
INTERNALERROR> AttributeError: 'NoneType' object has no attribute 'testscollected'

============================================================================================== 36 tests deselected ==============================================================================================

Results (0.57s):
       1 passed
      36 deselected
ERROR: InvocationError: '/Users/bullocm/git/aws-encryption-sdk-cli/.tox/py27-local/bin/pytest -m local -l'
____________________________________________________________________________________________________ summary ____________________________________________________________________________________________________
ERROR:   py27-local: commands failed
````

**Comment by mattsb42-aws** [comment]
Closing: looks like @jakewan opened #132 at almost the same time as this, and that's the one that got picked up.
