### ISSUE TITLE
IndexError: string index out of range (progressbar, pytest-testmon)

### ISSUE THREAD

**Issue by blueyed** [Frozenball/pytest-sugar#142]
I am seeing an IndexError sometimes when using pytest-sugar with pytest-testmon:

```
INTERNALERROR>   File "…/project/.venv/lib/python3.6/site-packages/pytest_sugar.py", line 305, in get_progress_bar
INTERNALERROR>     progressbar += colored(bar[block],
INTERNALERROR> IndexError: string index out of range
```

Full output:

```
% pytest --testmon
Test session starts (platform: linux, Python 3.6.6, pytest 3.7.3, pytest-sugar 0.9.1)                                                                                                        
Using --randomly-seed=1535462430                                                              
Django settings: project.settings (from environment variable)                                                                                                                              
testmon=True, changed files: 9, skipping collection of 62 files, run variant: 9630bf1e6f7851ea3bd508234ae41eee
rootdir: …/project/project, inifile: setup.cfg                                                                                                                           
plugins: requests-mock-1.5.2, testmon-0.9.13, sugar-0.9.1, repeat-0.6.0, randomly-1.2.3, pdb-0.3.1, mock-1.10.0, forked-0.2, cov-2.5.1, asyncio-0.9.0, celery-4.2.1, django-3.4.2.dev3+ng7d5b2
d9, xdist-1.22.6.dev1+g96af694.d20180828                                                                                                                                                     

 project/app/tests/test_api_clusters.py ✓✓✓✓✓✓✓✓✓✓                         100% ██████████INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "…/project/.venv/lib/python3.6/site-packages/_pytest/main.py", line 178, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "…/project/.venv/lib/python3.6/site-packages/_pytest/main.py", line 215, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "…/project/.venv/lib/python3.6/site-packages/pluggy/hooks.py", line 258, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "…/project/.venv/lib/python3.6/site-packages/pluggy/manager.py", line 67, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "…/project/.venv/lib/python3.6/site-packages/pluggy/manager.py", line 61, in <lambda>
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>   File "…/project/.venv/lib/python3.6/site-packages/pluggy/callers.py", line 201, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "…/project/.venv/lib/python3.6/site-packages/pluggy/callers.py", line 76, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "…/project/.venv/lib/python3.6/site-packages/pluggy/callers.py", line 180, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "…/project/.venv/lib/python3.6/site-packages/_pytest/main.py", line 236, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "…/project/.venv/lib/python3.6/site-packages/pluggy/hooks.py", line 258, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "…/project/.venv/lib/python3.6/site-packages/pluggy/manager.py", line 67, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "…/project/.venv/lib/python3.6/site-packages/pluggy/manager.py", line 61, in <lambda>
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>   File "…/project/.venv/lib/python3.6/site-packages/pluggy/callers.py", line 201, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "…/project/.venv/lib/python3.6/site-packages/pluggy/callers.py", line 76, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "…/project/.venv/lib/python3.6/site-packages/pluggy/callers.py", line 180, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "…/project/.venv/lib/python3.6/site-packages/_pytest/runner.py", line 66, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "…/project/.venv/lib/python3.6/site-packages/_pytest/runner.py", line 82, in runtestprotocol
INTERNALERROR>     reports.append(call_and_report(item, "teardown", log, nextitem=nextitem))
INTERNALERROR>   File "…/project/.venv/lib/python3.6/site-packages/_pytest/runner.py", line 165, in call_and_report
INTERNALERROR>     hook.pytest_runtest_logreport(report=report)
INTERNALERROR>   File "…/project/.venv/lib/python3.6/site-packages/pluggy/hooks.py", line 258, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "…/project/.venv/lib/python3.6/site-packages/pluggy/manager.py", line 67, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "…/project/.venv/lib/python3.6/site-packages/pluggy/manager.py", line 61, in <lambda>
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>   File "…/project/.venv/lib/python3.6/site-packages/pluggy/callers.py", line 201, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "…/project/.venv/lib/python3.6/site-packages/pluggy/callers.py", line 76, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "…/project/.venv/lib/python3.6/site-packages/pluggy/callers.py", line 180, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "…/project/.venv/lib/python3.6/site-packages/pytest_sugar.py", line 427, in pytest_runtest_logreport
INTERNALERROR>     self.insert_progress(report)
INTERNALERROR>   File "…/project/.venv/lib/python3.6/site-packages/pytest_sugar.py", line 318, in insert_progress
INTERNALERROR>     append_string = get_progress_bar()
INTERNALERROR>   File "…/project/.venv/lib/python3.6/site-packages/pytest_sugar.py", line 305, in get_progress_bar
INTERNALERROR>     progressbar += colored(bar[block],
INTERNALERROR> IndexError: string index out of range


Results (325.47s):
    1201 passed
       1 failed
         - project/app/tests/test_api_users.py:1026 test_email_register_whitelabel_race
       5 xfailed
       1 skipped
     215 deselected
```

I have not yet investigated myself, but wanted to file this already.

**Comment by max-sixty** [comment]
I frequently see this with `--testmon`

**Comment by blueyed** [comment]
@max-sixty 
Please try if https://github.com/Frozenball/pytest-sugar/pull/144 fixes it.

**Comment by max-sixty** [comment]
It does! Thank you @blueyed !
