### ISSUE TITLE
Test failures under pytest 4.1.0 and 4.2.0

### ISSUE THREAD

**Issue by matoro** [Frozenball/pytest-sugar#167]
Internal tests run with the command:

```
/usr/bin/python3.6 /usr/bin/pytest --cov --cov-config=.coveragerc test_sugar.py
```

fail with the following output:

```
platform linux -- Python 3.6.6, pytest-4.1.0, py-1.5.4, pluggy-0.7.1
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/var/tmp/portage/dev-python/pytest-sugar-0.9.2/work/pytest-sugar-0.9.2/.hypothesis/examples')
rootdir: /var/tmp/portage/dev-python/pytest-sugar-0.9.2/work/pytest-sugar-0.9.2, inifile:
plugins: sugar-0.9.2, sanic-0.1.15, cov-2.5.1, asyncio-0.10.0, hypothesis-3.85.1, celery-4.1.0, case-1.5.3
collected 28 items

FAILURES

TestTerminalReporter.test_item_count_after_pytest_collection_modifyitems

self = <test_sugar.TestTerminalReporter object at 0xb3bc0090>, testdir = <Testdir local('/var/tmp/portage/dev-python/pytest-sugar-0.9.2/temp/pytest-of-portage/pytest-0/test_item_count_after_pytest_collection_modifyitems0')>

    def test_item_count_after_pytest_collection_modifyitems(self, testdir):
        testdir.makeconftest(
            """
            import pytest
    
            @pytest.hookimpl(hookwrapper=True, tryfirst=True)
            def pytest_collection_modifyitems(config, items):
                yield
                items[:] = [x for x in items if x.name == 'test_one']
            """
        )
        testdir.makepyfile(
            """
            def test_one():
                print('test_one_passed')
    
            def test_ignored():
                assert 0
            """
        )
        result = testdir.runpytest('-p no:sugar', '-s')
        result.stdout.fnmatch_lines([
            '*test_one_passed*',
>           '*100%*',
        ])
E       Failed: nomatch: '*test_one_passed*'
E           and: ''
E       remains unmatched: '*test_one_passed*'

../../../../work/pytest-sugar-0.9.2/test_sugar.py:275: Failed

Captured stderr call

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/_pytest/config/__init__.py", line 530, in import_plugin
    __import__(importspec)
ModuleNotFoundError: No module named ' no:sugar'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/_pytest/pytester.py", line 889, in runpytest_inprocess
    reprec = self.inline_run(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/_pytest/pytester.py", line 856, in inline_run
    ret = pytest.main(list(args), plugins=plugins)
  File "/usr/lib/python3.6/site-packages/_pytest/config/__init__.py", line 61, in main
    config = _prepareconfig(args, plugins)
  File "/usr/lib/python3.6/site-packages/_pytest/config/__init__.py", line 196, in _prepareconfig
    pluginmanager=pluginmanager, args=args
  File "/usr/lib/python3.6/site-packages/pluggy/hooks.py", line 258, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/usr/lib/python3.6/site-packages/pluggy/manager.py", line 67, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/lib/python3.6/site-packages/pluggy/manager.py", line 61, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "/usr/lib/python3.6/site-packages/pluggy/callers.py", line 196, in _multicall
    gen.send(outcome)
  File "/usr/lib/python3.6/site-packages/_pytest/helpconfig.py", line 93, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/usr/lib/python3.6/site-packages/pluggy/callers.py", line 76, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/lib/python3.6/site-packages/pluggy/callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "/usr/lib/python3.6/site-packages/_pytest/config/__init__.py", line 652, in pytest_cmdline_parse
    self.parse(args)
  File "/usr/lib/python3.6/site-packages/_pytest/config/__init__.py", line 838, in parse
    self._preparse(args, addopts=addopts)
  File "/usr/lib/python3.6/site-packages/_pytest/config/__init__.py", line 780, in _preparse
    self.pluginmanager.consider_preparse(args)
  File "/usr/lib/python3.6/site-packages/_pytest/config/__init__.py", line 483, in consider_preparse
    self.consider_pluginarg(parg)
  File "/usr/lib/python3.6/site-packages/_pytest/config/__init__.py", line 497, in consider_pluginarg
    self.import_plugin(arg)
  File "/usr/lib/python3.6/site-packages/_pytest/config/__init__.py", line 539, in import_plugin
    six.reraise(new_exc_type, new_exc, sys.exc_info()[2])
  File "/usr/lib/python3.6/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.6/site-packages/_pytest/config/__init__.py", line 530, in import_plugin
    __import__(importspec)
ImportError: Error importing plugin " no:sugar": No module named ' no:sugar'

----------- coverage: platform linux, python 3.6.6-final-0 -----------
Name                                                                                                                                                   Stmts   Miss  Cover
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/var/tmp/portage/dev-python/pytest-sugar-0.9.2/temp/pytest-of-portage/pytest-0/test_collect_error0/test_collect_error.py                                   1      0   100%
/var/tmp/portage/dev-python/pytest-sugar-0.9.2/temp/pytest-of-portage/pytest-0/test_deselecting_tests0/test_deselecting_tests.py                           5      0   100%
/var/tmp/portage/dev-python/pytest-sugar-0.9.2/temp/pytest-of-portage/pytest-0/test_doctest0/test_doctest.py                                               2      0   100%
/var/tmp/portage/dev-python/pytest-sugar-0.9.2/temp/pytest-of-portage/pytest-0/test_error_in_setup_then_pass0/test_error_in_setup_then_pass.py             8      1    88%
/var/tmp/portage/dev-python/pytest-sugar-0.9.2/temp/pytest-of-portage/pytest-0/test_error_in_teardown_then_pass0/test_error_in_teardown_then_pass.py       8      0   100%
/var/tmp/portage/dev-python/pytest-sugar-0.9.2/temp/pytest-of-portage/pytest-0/test_fail0/test_fail.py                                                     3      0   100%
/var/tmp/portage/dev-python/pytest-sugar-0.9.2/temp/pytest-of-portage/pytest-0/test_fail_fail0/test_fail_fail.py                                           5      0   100%
/var/tmp/portage/dev-python/pytest-sugar-0.9.2/temp/pytest-of-portage/pytest-0/test_fail_in_fixture_and_test0/test_fail_in_fixture_and_test.py             9      1    89%
/var/tmp/portage/dev-python/pytest-sugar-0.9.2/temp/pytest-of-portage/pytest-0/test_fail_unicode_crashline0/test_fail_unicode_crashline.py                 3      0   100%
/var/tmp/portage/dev-python/pytest-sugar-0.9.2/temp/pytest-of-portage/pytest-0/test_new_summary0/test_new_summary.py                                       3      0   100%
/var/tmp/portage/dev-python/pytest-sugar-0.9.2/temp/pytest-of-portage/pytest-0/test_old_summary0/test_old_summary.py                                       3      0   100%
/var/tmp/portage/dev-python/pytest-sugar-0.9.2/temp/pytest-of-portage/pytest-0/test_report_header0/conftest.py                                             2      0   100%
/var/tmp/portage/dev-python/pytest-sugar-0.9.2/temp/pytest-of-portage/pytest-0/test_report_header0/test_report_header.py                                   2      0   100%
/var/tmp/portage/dev-python/pytest-sugar-0.9.2/temp/pytest-of-portage/pytest-0/test_skipping_tests0/test_skipping_tests.py                                 3      1    67%
/var/tmp/portage/dev-python/pytest-sugar-0.9.2/temp/pytest-of-portage/pytest-0/test_teardown_errors0/test_teardown_errors.py                               6      0   100%
/var/tmp/portage/dev-python/pytest-sugar-0.9.2/temp/pytest-of-portage/pytest-0/test_verbose0/test_verbose.py                                              13      1    92%
/var/tmp/portage/dev-python/pytest-sugar-0.9.2/temp/pytest-of-portage/pytest-0/test_verbose_has_double_colon0/test_verbose_has_double_colon.py             2      0   100%
/var/tmp/portage/dev-python/pytest-sugar-0.9.2/temp/pytest-of-portage/pytest-0/test_xfail_false0/test_xfail_false.py                                       3      0   100%
/var/tmp/portage/dev-python/pytest-sugar-0.9.2/temp/pytest-of-portage/pytest-0/test_xfail_strict_false0/test_xfail_strict_false.py                         3      0   100%
/var/tmp/portage/dev-python/pytest-sugar-0.9.2/temp/pytest-of-portage/pytest-0/test_xfail_strict_true0/test_xfail_strict_true.py                           3      0   100%
/var/tmp/portage/dev-python/pytest-sugar-0.9.2/temp/pytest-of-portage/pytest-0/test_xfail_true0/test_xfail_true.py                                         3      0   100%
/var/tmp/portage/dev-python/pytest-sugar-0.9.2/temp/pytest-of-portage/pytest-0/test_xpass_false0/test_xpass_false.py                                       3      0   100%
/var/tmp/portage/dev-python/pytest-sugar-0.9.2/temp/pytest-of-portage/pytest-0/test_xpass_strict0/test_xpass_strict.py                                     3      0   100%
/var/tmp/portage/dev-python/pytest-sugar-0.9.2/temp/pytest-of-portage/pytest-0/test_xpass_true0/test_xpass_true.py                                         3      0   100%
/var/tmp/portage/dev-python/pytest-sugar-0.9.2/work/pytest-sugar-0.9.2-python3_6/lib/pytest_sugar.py                                                     340    117    66%
test_sugar.py                                                                                                                                            137     13    91%
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
TOTAL                                                                                                                                                    576    134    77%

1 failed, 77 passed, 4 skipped in 46.13 seconds
```

**Comment by blueyed** [comment]
I see a different one also, caused by https://github.com/pytest-dev/pytest/commit/0f546c4670146fbb89407cad85518e3a7dcfa833:

```
% pytest -k test_collect_error
Test session starts (platform: linux, Python 3.7.2, pytest 4.2.1.dev64+g67dd10de, pytest-sugar 0.9.2)
rootdir: …/Vcs/pytest-sugar, inifile:
plugins: sugar-0.9.2
collecting ...

――――――――――――――――――――――― TestTerminalReporter.test_collect_error ―――――――――――――――――――――――

self = <test_sugar.TestTerminalReporter object at 0x7f8d69310278>
testdir = <Testdir local('/tmp/pytest-of-user/pytest-773/test_collect_error0')>

    def test_collect_error(self, testdir):
        testdir.makepyfile("""raise ValueError(0)""")
        assert_count(testdir)
        result = testdir.runpytest('--force-sugar')
        result.stdout.fnmatch_lines([
            "*ERROR collecting test_collect_error.py*",
            "test_collect_error.py:1: in <module>",
            "    raise ValueError(0)",
>           "E   ValueError: 0",
        ])
E       Failed: nomatch: '*ERROR collecting test_collect_error.py*'
E           and: 'Test session starts (platform: linux, Python 3.7.2, pytest 4.2.1.dev64+g67dd10de, pytest-sugar 0.9.2)'
E           and: 'rootdir: /tmp/pytest-of-user/pytest-773/test_collect_error0, inifile:'
E           and: 'plugins: sugar-0.9.2'
E           and: '\r'
E           and: '―――――――――――――――――――――――――――― test_collect_error.py ―――――――――――――――――――――――――――――'
E           and: 'test_collect_error.py:1: in <module>'
E           and: '    raise ValueError(0)'
E           and: 'E   ValueError: 0'
E           and: ''
E           and: '!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!'
E           and: ''
E           and: 'Results (0.04s):'
E           and: ''
E       remains unmatched: '*ERROR collecting test_collect_error.py*'

…/Vcs/pytest-sugar/test_sugar.py:430: Failed
-------------------------------- Captured stdout call ---------------------------------
============================= test session starts ==============================
platform linux -- Python 3.7.2, pytest-4.2.1.dev64+g67dd10de, py-1.7.0, pluggy-0.8.1
rootdir: /tmp/pytest-of-user/pytest-773/test_collect_error0, inifile:
collected 0 items / 1 errors

==================================== ERRORS ====================================
____________________ ERROR collecting test_collect_error.py ____________________
test_collect_error.py:1: in <module>
    raise ValueError(0)
E   ValueError: 0
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
=========================== 1 error in 0.06 seconds ============================
Test session starts (platform: linux, Python 3.7.2, pytest 4.2.1.dev64+g67dd10de, pytest-sugar 0.9.2)
rootdir: /tmp/pytest-of-user/pytest-773/test_collect_error0, inifile:
plugins: sugar-0.9.2

―――――――――――――――――――――――――――― test_collect_error.py ―――――――――――――――――――――――――――――
test_collect_error.py:1: in <module>
    raise ValueError(0)
E   ValueError: 0

!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!

Results (0.05s):
Test session starts (platform: linux, Python 3.7.2, pytest 4.2.1.dev64+g67dd10de, pytest-sugar 0.9.2)
rootdir: /tmp/pytest-of-user/pytest-773/test_collect_error0, inifile:
plugins: sugar-0.9.2

―――――――――――――――――――――――――――― test_collect_error.py ―――――――――――――――――――――――――――――
test_collect_error.py:1: in <module>
    raise ValueError(0)
E   ValueError: 0

!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!

Results (0.04s):

 test_sugar.py ⨯                                                        100% ██████████

Results (0.25s):
       1 failed
         - test_sugar.py:422 TestTerminalReporter.test_collect_error
      27 deselected
```

**Comment by blueyed** [comment]
See https://github.com/Frozenball/pytest-sugar/pull/169 for the failure you've reported.
