### ISSUE TITLE
Fails with --lf option of pytest-cache

### ISSUE THREAD

**Issue by fschulze** [Frozenball/pytest-sugar#37]
When using the --lf option of pytest-cache to only run tests that failed last time, this exception is raised:
```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "./lib/python3.4/site-packages/_pytest/main.py", line 84, in wrap_session
INTERNALERROR>     doit(config, session)
INTERNALERROR>   File "./lib/python3.4/site-packages/_pytest/main.py", line 122, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "./lib/python3.4/site-packages/_pytest/core.py", line 413, in __call__
INTERNALERROR>     return self._docall(methods, kwargs)
INTERNALERROR>   File "./lib/python3.4/site-packages/_pytest/core.py", line 424, in _docall
INTERNALERROR>     res = mc.execute()
INTERNALERROR>   File "./lib/python3.4/site-packages/_pytest/core.py", line 315, in execute
INTERNALERROR>     res = method(**kwargs)
INTERNALERROR>   File "./lib/python3.4/site-packages/_pytest/main.py", line 142, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "./lib/python3.4/site-packages/_pytest/core.py", line 413, in __call__
INTERNALERROR>     return self._docall(methods, kwargs)
INTERNALERROR>   File "./lib/python3.4/site-packages/_pytest/core.py", line 424, in _docall
INTERNALERROR>     res = mc.execute()
INTERNALERROR>   File "./lib/python3.4/site-packages/_pytest/core.py", line 315, in execute
INTERNALERROR>     res = method(**kwargs)
INTERNALERROR>   File "./lib/python3.4/site-packages/pytest_timeout.py", line 72, in pytest_runtest_protocol
INTERNALERROR>     return __multicall__.execute()
INTERNALERROR>   File "./lib/python3.4/site-packages/_pytest/core.py", line 315, in execute
INTERNALERROR>     res = method(**kwargs)
INTERNALERROR>   File "./lib/python3.4/site-packages/_pytest/runner.py", line 65, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "./lib/python3.4/site-packages/_pytest/runner.py", line 77, in runtestprotocol
INTERNALERROR>     nextitem=nextitem))
INTERNALERROR>   File "./lib/python3.4/site-packages/_pytest/runner.py", line 113, in call_and_report
INTERNALERROR>     hook.pytest_runtest_logreport(report=report)
INTERNALERROR>   File "./lib/python3.4/site-packages/_pytest/main.py", line 166, in call_matching_hooks
INTERNALERROR>     return hookmethod.pcall(plugins, **kwargs)
INTERNALERROR>   File "./lib/python3.4/site-packages/_pytest/core.py", line 417, in pcall
INTERNALERROR>     return self._docall(methods, kwargs)
INTERNALERROR>   File "./lib/python3.4/site-packages/_pytest/core.py", line 424, in _docall
INTERNALERROR>     res = mc.execute()
INTERNALERROR>   File "./lib/python3.4/site-packages/_pytest/core.py", line 315, in execute
INTERNALERROR>     res = method(**kwargs)
INTERNALERROR>   File "./lib/python3.4/site-packages/pytest_sugar.py", line 230, in pytest_runtest_logreport
INTERNALERROR>     self.overwrite(self.insert_progress())
INTERNALERROR>   File "./lib/python3.4/site-packages/pytest_sugar.py", line 180, in insert_progress
INTERNALERROR>     append_string = get_progress_bar()
INTERNALERROR>   File "./lib/python3.4/site-packages/pytest_sugar.py", line 173, in get_progress_bar
INTERNALERROR>     progressbar += PROGRESS_BAR_BLOCKS[14 - rem]
INTERNALERROR> IndexError: list index out of range
```

**Comment by icemac** [comment]
As #39 is merged this issue can be set to solved.
