### ISSUE TITLE
Doesn't work with pytest-xdist

### ISSUE THREAD

**Issue by thedrow** [Frozenball/pytest-sugar#64]
I'm getting:
```
[gw54] linux2 Python 2.7.10 cwd: /home/omer/Documents/Projects/zBackend/devices/malware/tests/functional
gw53 C / gw54 CINTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/omer/Documents/Projects/zBackend/.tox/py27-malware-functional/lib/python2.7/site-packages/_pytest/main.py", line 80, in wrap_session
INTERNALERROR>     config.do_configure()
INTERNALERROR>   File "/home/omer/Documents/Projects/zBackend/.tox/py27-malware-functional/lib/python2.7/site-packages/_pytest/config.py", line 618, in do_configure
INTERNALERROR>     self.hook.pytest_configure(config=self)
INTERNALERROR>   File "/home/omer/Documents/Projects/zBackend/.tox/py27-malware-functional/lib/python2.7/site-packages/_pytest/core.py", line 521, in __call__
INTERNALERROR>     return self._docall(self.methods, kwargs)
INTERNALERROR>   File "/home/omer/Documents/Projects/zBackend/.tox/py27-malware-functional/lib/python2.7/site-packages/_pytest/core.py", line 528, in _docall
INTERNALERROR>     firstresult=self.firstresult).execute()
INTERNALERROR>   File "/home/omer/Documents/Projects/zBackend/.tox/py27-malware-functional/lib/python2.7/site-packages/_pytest/core.py", line 394, in execute
INTERNALERROR>     res = method(*args)
INTERNALERROR>   File "/home/omer/Documents/Projects/zBackend/.tox/py27-malware-functional/lib/python2.7/site-packages/pytest_sugar.py", line 122, in pytest_configure
INTERNALERROR>     sugar_reporter = SugarTerminalReporter(standard_reporter)
INTERNALERROR>   File "/home/omer/Documents/Projects/zBackend/.tox/py27-malware-functional/lib/python2.7/site-packages/pytest_sugar.py", line 148, in __init__
INTERNALERROR>     TerminalReporter.__init__(self, reporter.config)
INTERNALERROR> AttributeError: 'NoneType' object has no attribute 'config'
[gw53] node down: Not properly terminated
```
I'd rather have a responsive CI than a pretty looking log output but if possible I'd like to have both.
Any idea what's broken here?

**Comment by RonnyPfannschmidt** [comment]
from the looks of it the plugin doesn't disable itself on a slave node

for easier ci turnaround you can use `py.test -p no:sugar` to completely disable the plugin
my current guess is that the plugin should work fine if it does the turnaround with disabling itself if there is a `config.slaveinput`

**Comment by thedrow** [comment]
I'd rather override the xdist output and get the sugered output instead.

**Comment by RonnyPfannschmidt** [comment]
a xdist slave has no output, only the master has,

so teach sugar only to do output on the master
