### ISSUE TITLE
UnboundLocalError when used together with pytest-rerunfailures

### ISSUE THREAD

**Issue by icemac** [Frozenball/pytest-sugar#80]
I am using pytest-sugar together with pytest-rerunfailures (version 1.0.1) and marked a test using `@pytest.mark.flaky(reruns=3)`. When this test ist run again because it failed I get the following internal error:

```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File ".../pytest-2.7.3-py2.7.egg/_pytest/main.py", line 84, in wrap_session
INTERNALERROR>     doit(config, session)
INTERNALERROR>   File ".../pytest-2.7.3-py2.7.egg/_pytest/main.py", line 122, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File ".../pytest-2.7.3-py2.7.egg/_pytest/core.py", line 521, in __call__
INTERNALERROR>     return self._docall(self.methods, kwargs)
INTERNALERROR>   File ".../pytest-2.7.3-py2.7.egg/_pytest/core.py", line 528, in _docall
INTERNALERROR>     firstresult=self.firstresult).execute()
INTERNALERROR>   File ".../pytest-2.7.3-py2.7.egg/_pytest/core.py", line 394, in execute
INTERNALERROR>     res = method(*args)
INTERNALERROR>   File ".../pytest-2.7.3-py2.7.egg/_pytest/main.py", line 142, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File ".../pytest-2.7.3-py2.7.egg/_pytest/core.py", line 521, in __call__
INTERNALERROR>     return self._docall(self.methods, kwargs)
INTERNALERROR>   File ".../pytest-2.7.3-py2.7.egg/_pytest/core.py", line 528, in _docall
INTERNALERROR>     firstresult=self.firstresult).execute()
INTERNALERROR>   File ".../pytest-2.7.3-py2.7.egg/_pytest/core.py", line 393, in execute
INTERNALERROR>     return wrapped_call(method(*args), self.execute)
INTERNALERROR>   File ".../pytest-2.7.3-py2.7.egg/_pytest/core.py", line 113, in wrapped_call
INTERNALERROR>     return call_outcome.get_result()
INTERNALERROR>   File ".../pytest-2.7.3-py2.7.egg/_pytest/core.py", line 138, in get_result
INTERNALERROR>     py.builtin._reraise(*ex)
INTERNALERROR>   File ".../pytest-2.7.3-py2.7.egg/_pytest/core.py", line 123, in __init__
INTERNALERROR>     self.result = func()
INTERNALERROR>   File ".../pytest-2.7.3-py2.7.egg/_pytest/core.py", line 394, in execute
INTERNALERROR>     res = method(*args)
INTERNALERROR>   File "build/bdist.macosx-10.11-x86_64/egg/pytest_rerunfailures.py", line 86, in pytest_runtest_protocol
INTERNALERROR>     item.ihook.pytest_runtest_logreport(report=report)
INTERNALERROR>   File ".../pytest-2.7.3-py2.7.egg/_pytest/core.py", line 521, in __call__
INTERNALERROR>     return self._docall(self.methods, kwargs)
INTERNALERROR>   File ".../pytest-2.7.3-py2.7.egg/_pytest/core.py", line 528, in _docall
INTERNALERROR>     firstresult=self.firstresult).execute()
INTERNALERROR>   File ".../pytest-2.7.3-py2.7.egg/_pytest/core.py", line 394, in execute
INTERNALERROR>     res = method(*args)
INTERNALERROR>   File ".../pytest_sugar-0.6.0-py2.7.egg/pytest_sugar.py", line 353, in pytest_runtest_logreport
INTERNALERROR>     res = pytest_report_teststatus(report=report)
INTERNALERROR>   File ".../pytest_sugar-0.6.0-py2.7.egg/pytest_sugar.py", line 166, in pytest_report_teststatus
INTERNALERROR>     return report.outcome, letter, report.outcome.upper()
INTERNALERROR> UnboundLocalError: local variable 'letter' referenced before assignment
```

**Comment by icemac** [comment]
Version 0.05 of pytest-rerunfailures does not trigger this error. So it might be caused by a change there but the `UnboundLocalError` here is not the expected behavior, too.

**Comment by Frozenball** [comment]
Thanks for the bug report, I have fixed this for the next release.

**Comment by hangtwenty** [comment]
Just got this with pytest-sugar 0.9.1. Here are all my pytest-related dependencies:

```
$ pip freeze | grep pytest
pytest==3.5.1
pytest-cov==2.5.1
pytest-django==3.2.1
pytest-env==0.6.2
pytest-forked==0.2
pytest-rerunfailures==4.1
pytest-sugar==0.9.1
pytest-xdist==1.22.2
```
