### ISSUE TITLE
Traceback for --new-summary

### ISSUE THREAD

**Issue by icemac** [Frozenball/pytest-sugar#95]
Call: `py.test --new-summary --lf`

Result:

```
Traceback (most recent call last):
  File "bin/py.test", line 350, in <module>
    sys.exit(pytest.main())
  File "/.../pytest-2.9.0-py2.7.egg/_pytest/config.py", line 49, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "/.../pytest-2.9.0-py2.7.egg/_pytest/vendored_packages/pluggy.py", line 724, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/.../pytest-2.9.0-py2.7.egg/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/.../pytest-2.9.0-py2.7.egg/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/.../pytest-2.9.0-py2.7.egg/_pytest/vendored_packages/pluggy.py", line 596, in execute
    res = hook_impl.function(*args)
  File "/.../pytest-2.9.0-py2.7.egg/_pytest/main.py", line 119, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/.../pytest-2.9.0-py2.7.egg/_pytest/main.py", line 114, in wrap_session
    exitstatus=session.exitstatus)
  File "/.../pytest-2.9.0-py2.7.egg/_pytest/vendored_packages/pluggy.py", line 724, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/.../pytest-2.9.0-py2.7.egg/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/.../pytest-2.9.0-py2.7.egg/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/.../pytest-2.9.0-py2.7.egg/_pytest/vendored_packages/pluggy.py", line 595, in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
  File "/.../pytest-2.9.0-py2.7.egg/_pytest/vendored_packages/pluggy.py", line 249, in _wrapped_call
    wrap_controller.send(call_outcome)
  File "/.../pytest-2.9.0-py2.7.egg/_pytest/terminal.py", line 378, in pytest_sessionfinish
    self.summary_stats()
  File "/.../pytest_sugar-0.7.1-py2.7.egg/pytest_sugar.py", line 419, in summary_stats
    path, name = report.location[0].rsplit('/', 1)
ValueError: need more than 1 value to unpack
```

`report.location[0]` was `'test_suite'` in this case.

`report.location` was: `('test_suite', None, '/src/my.package/src/my/package/composer/tests/../documentedit.txt')`.

So `report.location[2]` could be used for the split in this case. Accessing `report.location[1]` a few lines later should be adapted to be able to handle the `None` value.

**Comment by icemac** [comment]
This problem also occurred to me on another project when calling _without_ `--lf`.

**Comment by Frozenball** [comment]
This is a good catch and it's also very stupid flaw in the code
